### ISSUE TITLE
Does this work with the PFC100?

### ISSUE THREAD

**Issue by TheColonel2688** [braunku/pfc-provisioning-tool#1]
Does this tool work with the PFC100 yet?

**Comment by braunku** [comment]
Generally no, because the PFC100 does not officially support docker due to limited flash memory.  There is a workaround to running off the SD card as the file system, in which case this tool would work correctly. 

Consult the Wago community for a how-to on this.
https://www.wago.community/t/how-to-using-docker-on-the-pfc100-sd-card/69
